export const BBOM_AUTH_FORGOT_PASSWORD_VALIDATIONS_FORMAT = "BBOM-AUTH-FORGOT-PASSWORD-VALIDATIONS-FORMAT";
export const BBOM_AUTH_FORGOT_PASSWORD_CONNECTION_BURM = "BBOM-AUTH-FORGOT-PASSWORD-CONNECTION-BURM";
export const BBOM_AUTH_FORGOT_PASSWORD_CONNECTION_BCPM = "BBOM-AUTH-FORGOT-PASSWORD-CONNECTION-BCPM";
export const BBOM_AUTH_FORGOT_PASSWORD_INTERNAL_SERVER_ERROR = "BBOM-AUTH-FORGOT-PASSWORD-INTERNAL-SERVER-ERROR";
